# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testdockeryelloji

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockeryelloji.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e43f435550534fd9ae477d073353236f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c094eed4d4bb4e198d8905a7ebc7ec3a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockeryelloji.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e43f435550534fd9ae477d073353236f }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testdockeryelloji'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_b5ce1d863a044d35b18cc5d631f433db }}
        images: 'testdockeryelloji.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e43f435550534fd9ae477d073353236f }}/studentperformance:${{ github.sha }}'